# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('FB', 'FaceBook'), ('KT', 'KaKaoTalk')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([('email', 'provider', 'uid', 'access_token')]),
        ),
    ]
