# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellaruser',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stellarsocialuser',
            name='provider',
            field=models.CharField(choices=[('KT', 'KaKaoTalk'), ('FB', 'FaceBook'), ('GG', 'Google')], max_length=10),
        ),
    ]
