# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180121_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('KT', 'KaKaoTalk'), ('FB', 'FaceBook')], max_length=30),
        ),
    ]
