# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 15:03
from __future__ import unicode_literals

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180224_2319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stellaruser',
            managers=[
                ('objects', user.models.StellarUserManager()),
            ],
        ),
    ]
