# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180225_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='TestPhoto', max_length=30),
            preserve_default=False,
        ),
    ]
