# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180225_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='lnglat',
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
